version: '1.0'
name: test
displayName: test
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-db52d565
    displayName: 测试
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: run_test
        certificate: ''
        image: ubuntu:20.04
        command:
          - '# 请在此输入您想执行的脚本'
          - apt-get update
          - apt-get install -y build-essential
          - cd test
          - make
          - ./main
        notify: []
        strategy:
          retry: '0'
