version: '1.0'
name: test
displayName: test
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-db52d565
    displayName: 测试
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: run_test
        certificate: ''
        image: hub.atomgit.com/amd64/ubuntu:23.10
        command:
          - '# 请在此输入您想执行的脚本'
          - apt-get update
          - apt-get install -y build-essential cmake git
          - git submodule update --init --recursive --depth=1
          - cd test
          - ./build.sh
          - ./build/test
        notify: []
        strategy:
          retry: '0'
